// Auto-generated symptoms list from symptoms_with_sheets_english.csv
// Total: 1397 symptoms
const recordSymptomsList = [
    'vaivarnya (वैवर्ण्य)',
    'syncope (murchchha, मूर्च्छा)',
    'fever (jvara, ज्वर)',
    'cough (kasa, कास)',
    'hiccups (hikka, हिक्का)',
    'asthama (shvasa, श्वास)',
    'change in taste of mouth (vairasya, वैरस्य)',
    'thirst (trisha, तृषा)',
    'severe syncope (pramoha:, प्रमोह:)',
    'vomiting (chhardi, छर्दी)',
    'repeatedly spit (kaphotklesha, कफोत्क्लेश)',
    'pain in chest or in other region (ruja, रुज)',
    'anorexia (aruchi, अरुची)',
    'hrichchhunya (हृच्छून्य)',
    'tachycardia (hridaya gati badhana, हृदय गति बढना)',
    'feeling of dryness in heart (hridaya shosha, हृदय शोष)',
    'hridaya bheda (हृदय भेद)',
    'stiffness of heart (hridaya stambha, हृदय स्तंभ)',
    'syncope (moha, मोह)',
    'tam (तम्)',
    'paritapa hona (परिताप होना)',
    'heart burn (hridaya daha, हृदय दाह)',
    'to be afraid (bhaya, भय)',
    'fever (samtapa, संताप)',
    'heat up (samtrasa, संत्रास)',
    'yellowing of body (sharira pittata, शरीर पित्तता)',
    'hridaya stabdhata (हृदय स्तब्धता)',
    'heaviness in heart (hridaya gurutva, हृदय गुरुत्व)',
    'stiffness in heart (hridaya stimita, हृदय स्तिमित)',
    'dribbling (praseka, प्रसेक)',
    'tamdra (तंद्रा)',
    'tridosha lakshana (त्रिदोष लक्षण)',
    'intense heart ache (tivra hridaya pida, तीव्र हृदय पीडा)',
    'pricking pain in heart (hridaya toda, हृदय तोद)',
    'itching of heart (hridaya kandu, हृदय कण्डू)',
    'tivra vamkshana ruja (तीव्र वंक्षण रुजा)',
    'severe pain in urinary bladder (tivra basti ruja, तीव्र बस्ति रुजा)',
    'intense pain in penis (tivra maimdhra ruja, तीव्र मैंढ्र रुजा)',
    'frequent urination in less quantity (svalpam muhurmuutra tyaga, स्वल्पं मुहुर्मूूत्र त्याग)',
    'yellow urine (pita mutratyaga, पीत मूत्रत्याग)',
    'blood in urine (saraktam mutratyaga, सारक्तं मूत्रत्याग)',
    'pain during urination (surujam mutratyaga, सुरूजं मूत्रत्याग)',
    'burning during urination (sadaha mutratyaga, सदाह मूत्रत्याग)',
    'difficulty in urination (krichhanmuhurmutraya, कृछान्मुहुर्मूत्रय)',
    'heaviness of urinary bladder (basti gurutva, बस्ति गुरुत्व)',
    'heaviness of penis (limga gurutva, लिंग गुरुत्व)',
    'swelling on penis (limga shotha, लिंग शोथ)',
    'sticky urine (mutram sapichchham, मूत्रं सपिच्छं)',
    'tridoshaja lakshana (त्रिदोषज लक्षण)',
    'obstruction in urination (mutrasya chenmargamupaiti ruddhava, मूत्रस्य चेन्मार्गमुपैती रुद्धवा)',
    'pain in urinary bladder (basti ruja, बस्ति रुजा)',
    'pain from scrotum to anus (sevani shula, सेवनी शूल)',
    'pain in penis (mehana shula, मेहन शूल)',
    'pain in urinary bladder (basti shula, बस्ति शूल)',
    'multiple streams of urine (vishirnadharam, विशिर्णधारं)',
    'repeatedly rubbing the penis by hand due to pain (mridanati maimdhra sa tu vedanarto, मृदनाति मैंढ्र स तू वेदनार्तो)',
    'frequent defeacation (muhu:shakrinmunchati, मुहु:शकृन्मुञ्चति)',
    'frequent urination (varamvara mutratyaga, वारंवार मूत्रत्याग)',
    'blood in urine (mutrayatiha sasrika, मूत्रयतीह सासृक)',
    '???????? (????????)',
    'pain in inguinal region (vamkshana shula, वंक्षण शूल)',
    'pain in penis (maimdhra shula, मैंढ्र शूल)',
    'scrotum growth (vrishanativritte, वृषणातिवृत्ते)',
    'painful urination (krichha mutra tyaga, कृछ मूत्र त्याग)',
    'little urination with intense pain (tivrarti  mutrena sahalpamalpamayati, तीव्रार्ति  मुत्रेण सहाल्पमल्पमायाति)',
    'bloating of urinary bladder (basti adhmana, बस्ति आध्मान)',
    'heaviness of urinary bladder (basti gauravata, बस्ति गौरवता)',
    'continuous desire for copulation (nitya strisambhoga vasana, नित्य स्त्रीसंभोग वासना)',
    'priyam vashyam striyam na yati limga kadachidyati va yadi (प्रियां वश्याम् स्त्रीयं न याति लिंग कडाचिद्याति वा यदि)',
    'difficulty in breathing (shvasarta, श्वासार्त)',
    'svinna gatra (स्विन्न गात्र)',
    'mlana shishna (म्लान शिश्न)',
    'absence of sperm (nirbijah, निर्बिजः)',
    'alpa prana (अल्प प्राण)',
    'loss of excitement (alpa harsha, अल्प हर्ष)',
    'pramadasu bhavennara: (प्रमादासु भवेन्नर:)',
    'pamdu varna: (पांडू वर्ण:)',
    'durbala (दुर्बल)',
    'hridayaroga (हृदयरोग)',
    'pamdu (पांडू)',
    'tamakashvasa (तमकश्वास)',
    'kamala (कामला)',
    'shrama (श्रम)',
    'vamana (वमन)',
    'atisara (अतिसार)',
    'udarashula (उदरशूल)',
    'kasa (कास)',
    'jvara (ज्वर)',
    'medhra shotha (मेढ्र शोथ)',
    'medhra shula (मेढ्र शूल)',
    'redness in penis (medhra lali, मेढ्र लाली)',
    'medhra sphotashcha tivra jayate limgapaka: (मेढ्र स्फोटाश्च तीव्र जायते लिंगपाक:)',
    'extension of skin of penis (mamsavriddhi, मांसवृद्धी)',
    'fast formation of abscesses on penis (medhre vrana: kshipra, मेढ्रे व्रण: क्षिप्र)',
    'vrane pulaka udaka samkasha: strava: shyava aruna prabha: (व्रणे पुलाक उदक संकाश: स्त्राव: श्याव अरुण प्रभ:)',
    'valayi kurute kathina parigraha (वलयी कुरुते कठीण परिग्रह)',
    'trishna (तृष्णा)',
    'bhrama (भ्रम)',
    'murchchha (मूर्च्छा)',
    'chhardi (छर्दी)',
    'reddish discharge from abscesses of penis (limga vrane rakta strava, लिंग व्रणे रक्त स्त्राव)',
    'blackish discharge from abscesses of penis (limga vrane krishna strava, लिंग व्रणे कृष्ण स्त्राव)',
    'blueish discharge from abscesses of penis (limga vrane nila strava, लिंग व्रणे नील स्त्राव)',
    'smelly discharge from abscesses of penis (limga vrane avila strava, लिंग व्रणे अविल स्त्राव)',
    'burning sensation with pain (limge agnineva cha dagdhasya tivro daha: savedana:, लिंगे अग्निनेव च दग्धस्य तिव्रो दाह: सवेदन:)',
    'basti shula (बस्ति शुल)',
    'vrishana shula (वृषण शुल)',
    'sivani shula (सीवनी शुल)',
    'vamkshana shula (वंक्षण शुल)',
    'sticky discharge from abscesses of penis (limge vrane pichchhila strava, लिंगे व्रणे पिच्छील स्त्राव)',
    'whitish discharge from abscesses of penis (limge vrane pamdu varni strava, लिंगे व्रणे पांडू वर्णी स्त्राव)',
    'swelling of penis decreases and it becomes immobile and with less discharge (limge shvayathu: jayate mamda: stimito alpastrava:, लिंगे श्वयथु: जायते मंद: स्तिमितो अल्पस्त्राव:)',
    'chirat cha pakam vrajati shighram va (चिरात् च पाकं व्रजति शीघ्रम् वा)',
    'krimi (कृमि)',
    'klidati (क्लिदति)',
    'puti gamdhi (पूति गंधि)',
    'mani vishiऱ्yate (मणि विशीऱ्यते)',
    'medhra vishiऱ्yate (मेढ्र विशीऱ्यते)',
    'mushka vishiऱ्yate (मुष्क विशीऱ्यते)',
    'dhatu kshinata (धातू क्षीणता)',
    'vivarna (विवर्ण)',
    'dina (दीन)',
    'causes another diseases (kshipram vyadhimatha shnute, क्षिप्रम् व्याधिमथा श्नूते)',
    'kshaya (क्षय)',
    'mrityu (मृत्यू)',
    'epilepsy (panipadam cha samshoshya, पाणिपादं च संशोष्य)',
    'epilepsy (sira samshoshya cha, सिरा संशोष्य च)',
    'epilepsy (snayu samshoshya cha, स्नायू संशोष्य च)',
    'epilepsy (kamdara samshoshya cha, कंडरा संशोष्य च)',
    'body stiffness (damda vatstabdhagatrasya damdaka, दंड वात्स्तब्धगात्रस्य दंडक)',
    'Hands stiffness (pani stabhnati maruta:, पाणि स्तभ्नाती मारुत:)',
    'legs stiffnesa (pada stabhnati maruta:, पाद स्तभ्नाती मारुत:)',
    'head stiffness (shira:stabhnati maruta:, शिर:स्तभ्नाती मारुत:)',
    'back stiffness (prishtha:stabhnati maruta:, पृष्ठ:स्तभ्नाती मारुत:)',
    'hip stiffness (shroni:stabhnati maruta:, श्रोणी:स्तभ्नाती मारुत:)',
    'stiffed mouth (vivritasyatvamathava, विवृतास्यत्वमथवा)',
    'stabdhavedanama (स्तब्धवेदनम)',
    'hanugraham cha samstabhya hanu samvritavakratama (हनुग्रहं च संस्तभ्य हनु संवृतवक्रताम)',
    'motionless (stabdha, स्तब्ध)',
    'hard to touch (kathina sparsha, कठीण स्पर्श)',
    'loose discharge (mamda strava, मंद स्त्राव)',
    'heavy pain (ati vrana ruk, अति व्रण रुक्)',
    'pricking pain (toda, तोद)',
    'sphurana (स्फुरण)',
    'shyava vrana (श्याव व्रण)',
    'thirsty (trishna, तृष्णा)',
    'unconsiousness (moha, मोह)',
    'fever (jvara, ज्वर)',
    'kleda (क्लेद)',
    'burning sensation (daha, दाह)',
    'dushtya vrana (दुष्ट्य व्रण)',
    'gamdha strava (गंध स्त्राव)',
    'bahupichchhila (बहुपिच्छिल)',
    'heaviness in body (guru, गुरु)',
    'snigdha (स्निग्ध)',
    'stimimto (स्तीमिंतो)',
    'slight pain (mamdavedana:, मंदवेदन:)',
    'panduvarna (पाण्डुवर्ण)',
    'loose discharge (alpasamkleda, अल्पसंक्लेद)',
    'chirakari vrana (चिरकारी व्रण)',
    'heavy discharge (parisravachcha, परिस्रावच्च)',
    'gamdhachcha (गंधच्च)',
    'doshachcho (दोषाच्चो)',
    'upadrave: saha (उपद्रवे: सह)',
    'tvakamamsaja: (त्वकमांसज:)',
    'sukha deshe (सुख देशे)',
    'tarunasya (तरुणस्या)',
    'anupadrava: (अनुपद्रव:)',
    'pain in inflammation (vedana, वेदना)',
    'redness in that region (raga, राग)',
    'piditonnotam (पिडितोन्नोतम्)',
    'jalabastisamasparsha (जलबस्तीसमस्पर्श)',
    'putigamdhanam (पूतिगंधानं)',
    'with distorted  color (vivarnacham, विवर्णाचं)',
    'heavy discharge (bahustrava, बहूस्त्राव)',
    'to much pain present (bahu ruja, बहु रुजा)',
    'natirakto (नतिरक्तो)',
    'nati pamdu nati shyava (नाति पांडू नाति श्याव)',
    'slight pain (na ati ruka, न अति रुक)',
    'na chotsanno (न चोत्सन्नो)',
    'na chotsamgi (न चोत्संगी)',
    'frothy vaginal bleeding (phenila asrika yonistrava, फेनिल असृक योनिस्त्राव)',
    'watery vaginal bleeding (tanu asrika yonistrava, तनु असृक योनिस्त्राव)',
    'dry vaginal bleeding (ruksha asrika yonistrava, रुक्ष असृक योनिस्त्राव)',
    'shyava asrika yonistrava (श्याव असृक योनिस्त्राव)',
    'reddish black vaginal bleeding (aruna asrika yonistrava, अरुण असृक योनिस्त्राव)',
    'sacred flower coloured vaginal bleeding (kimshuka udaka samkasha asrika yonistrava, किंशुक उदक संकाश असृक योनिस्त्राव)',
    'sometimes painful sometimes not (sarujam va nirujam, सरुजं वा निरूजं)',
    'kati shula (कटी शुल)',
    'vamkshana shula (वंक्षण शुल)',
    'hridaya shula (हृदय शुल)',
    'parshva shula (पार्श्व शुल)',
    'prishtha shula (पृष्ठ शुल)',
    'shroni shula (श्रोणि शुल)',
    'nila asrika yonistrava (नील असृक योनिस्त्राव)',
    'pita asrika yonistrava (पीत असृक योनिस्त्राव)',
    'extreme hot vaginal bleeding (ati ushna asrika yonistrava, अति उष्ण असृक योनिस्त्राव)',
    'nitamta raktam sravati muhurmuhurathartiman (नितांत रक्तम् स्रवति मुहूर्मुहुरथार्तिमान्)',
    'daha (दाह)',
    'raga (राग)',
    'trishna (तृष्णा)',
    'moha (मोह)',
    'jvara (ज्वर)',
    'bhrama (भ्रम)',
    'pichchhila asrika yonistrava (पिच्छील असृक योनिस्त्राव)',
    'pamdu asrika yonistrava (पांडु असृक योनिस्त्राव)',
    'heavy vaginal bleeding (guru asrika yonistrava, गुरु असृक योनिस्त्राव)',
    'balsamic vaginal bleeding (snigdha asrika yonistrava, स्निग्ध असृक योनिस्त्राव)',
    'cool vaginal bleeding (shitala asrika yonistrava, शीतल असृक योनिस्त्राव)',
    'vaginal bleeding with kapha (shleshmala asrika yonistrava, श्लेष्मल असृक योनिस्त्राव)',
    'compact vaginal bleeding (ghana asrika yonistrava, घन असृक योनिस्त्राव)',
    'alpavedana (अल्पवेदना)',
    'chchhardi (च्छर्दी)',
    'aruchi (अरुची)',
    'hrillasa (हृल्लास)',
    'shvasa (श्वास)',
    'kasa (कास)',
    'trilimga samyutam (त्रिलिंग संयुतं)',
    'ati pariklishta (अति परिक्लिष्ट)',
    'reduced vaginal bleeding (kshina asrika yonistrava, क्षीण असृक योनिस्त्राव)',
    'smelly vaginal bleeding (durgamdhi asrika yonistrava, दुर्गंधी असृक योनिस्त्राव)',
    'vidagdham pitta tejasa (विदग्धम् पित्त तेजसा)',
    'ghee like vaginal bleeding (sarpivat asrika yonistrava, सर्पिवत् असृक योनिस्त्राव)',
    'majja like vaginal bleeding (majjavat asrika yonistrava, मज्जावत् असृक योनिस्त्राव)',
    'Vasa like vaginal bleeding (vasavat asrika yonistrava, वसावत् असृक योनिस्त्राव)',
    'continuous vaginal bleeding (shashvata asrika yonistrava, शाश्वत असृक योनिस्त्राव)',
    'raktakshaya (रक्तक्षय)',
    'durbala (दुर्बल)',
    'laghuta puna: (लघुता पुन:)',
    'urinary obstruction (nigraho mutra, निग्रहो मूत्र)',
    'constipation (nigraho varchaso, निग्रहो वर्चसो)',
    'inguinal hernia (bradhnaroga, ब्रध्नरोग)',
    'heart disease (hridraroga, हृद्ररोग)',
    'gulma (गुल्म)',
    'piles (arsha, अर्श)',
    'parshvashula (पार्श्वशूल)',
    'gatrasphurana (गात्रस्फुरण)',
    'bhajjanama (भज्जनम)',
    'sphutantivasya samdhaya: (स्फुटन्तीवास्य संधय:)',
    'constipation (graho vina, ग्रहो विण)',
    'urinary obstruction (graho mutra, ग्रहो मूत्र)',
    'flatus obstruction (graho vatanam, ग्रहो वातानां)',
    'abdominal pain (shula, शूल)',
    'bloating (adhmana, आध्मान)',
    'urinary calculi (sharkara, शर्करा)',
    'urinary calculi (ashmari, अश्मरी)',
    'inguinal pain (jamgho rogashosho, जंघो रोगशोषो)',
    'pain in thighs (uru rogashosho, उरु रोगशोषो)',
    'sacral pain (trika rogashosho, त्रिक रोगशोषो)',
    'pain in leg region (pata rogashosho, पात रोगशोषो)',
    'back pain (prishtha rogashosho, पृष्ठ रोगशोषो)',
    'pain in heart (hrida ruka, हॄद रुक)',
    'pain in belly region (nabhiruka, नाभिरुक)',
    'parshvaruka (पार्श्वरुक)',
    'abdominal pain (udararuka, उदररुक)',
    'thirsty (trishna, तृष्णा)',
    'burping (uddgara, उद्द्गार)',
    'cholera (visuchika:, विसूचिका:)',
    'cough (kasa, कास)',
    'throat dryness (kamthasyashoshashcha, कंठास्यशोषश्च)',
    'dispnea on exertion (shvasa, श्वास)',
    'rumbling (antrakujana, आन्त्रकूजन)',
    'pain (shula, शूल)',
    'bloating (atopa, आटोप)',
    'urinary obstruction (mutrakrichchhra, मूत्रकृच्छ्र)',
    'constipation (purishatvam, पुरिषत्वं)',
    'anaha (आनाह)',
    'sacral pain (trikavedanama, त्रिकवेदनम)',
    'dryness of skin (tvagruruksha, त्वग्रुरुक्षा)',
    'tvaga sphutita (त्वग स्फुटिता)',
    'loss touch sensation (tvaga supta, त्वग सुप्ता)',
    'thinning of skin layer (tvaga krisha, त्वग कृशा)',
    'tvaga krishna (त्वग कृष्णा)',
    'pricking  pain (cha tudyate, च तुद्यते)',
    'atanyate (आतन्यते)',
    'saraga (सरागा)',
    'pain in joints (parva ruka, पर्व रुक)',
    'sasantapa (ससन्ताप)',
    'skin discoloration (vaivarnya, वैवर्ण्य)',
    'lean (krishata, कृशता)',
    'anorexia (aruchi, अरुचि)',
    'pimples (charumshi, चारुंषी)',
    'stiffeness of limbs after meal (gatre bhuktasya stambha, गात्रे भुक्तस्य स्तम्भ)',
    'heaviness of body (gurvamnga, गुर्वंङ्ग)',
    'dandamushtihatam (दण्डमुष्टिहतं)',
    'body ache (saruka, सरुक)',
    'shramitamatyartha (श्रमितमत्यर्थ)',
    'bhedoasthiparvanam (भेदोअस्थिपर्वणां)',
    'pain in joints (sandhishulam, सन्धिशूलं)',
    'muscle and strength vasting (mamsabalakshaya:, मांसबलक्षय:)',
    'insomnia (asvapna, अस्वप्न)',
    'body ache (santata ruka, सन्तता रुक)',
    'badhnati shukram (बध्नाति शुक्रं)',
    'badhnati garbhamathapi (बध्नाति गर्भमथापि)',
    'vikriti janayechchapi shukrastha: (विकृति जनयेच्चापि शुक्रस्थ:)',
    'bahyayama (बाह्यायाम)',
    'abhyamtarayama (आभ्यंतरायाम)',
    'khalli (खल्ली)',
    'kubja (कुब्ज)',
    'sarvangaroga (सर्वाङ्गरोग)',
    'ekangaroga (एकाङ्गरोग)',
    'sharira mandaruka (शरीर मन्दरुक)',
    'shopham (शोफं)',
    'shushyati (शुष्यति)',
    'spandate (स्पन्दते)',
    'suptastanyavayo (सुप्तास्तन्यवयो)',
    'sira vate siragate (सिरा वाते सिरागते)',
    'sphikpurva (स्फिक्पूर्वा)',
    'katiprishthorujanujamghapadam kramata (कटीपृष्ठोरुजानुजंघापदं क्रमात)',
    'pricking pain (stambharaktodai grihamti, स्तंभरक्तोदै गृहांति)',
    'spamdamte muhu: (स्पंदंते मुहु:)',
    'tamdra (तंद्रा)',
    'heaviness of body (gaurava, गौरव)',
    'arochaka (अरोचक)',
    'legs stiffness (padam, पादां)',
    'jamgho (जंघो)',
    'thighs stiffness (uru, उरु)',
    'wrist stiffness (karamula, करमूल)',
    'avamotani (अवमोटनी)',
    'tetanus (chapavannamyamanasya, चापवन्नाम्यमानस्य)',
    'prishthato (पृष्ठतो)',
    'niyate shira: (नियते शिर:)',
    'ura utikshipyate (उर उतिक्षिप्यते)',
    'neck stiffness (manya stabdha, मन्या स्तब्धा)',
    'grivavamridyate (ग्रीवावमृद्यते)',
    'damtanam dashanam (दंतानां दशनं)',
    'yawning (jrimbha, जृम्भा)',
    'dribling (lalastrava, लालास्त्राव)',
    'vaggraha: (वाग्ग्रह:)',
    'jatavego nihanatyesha (जातवेगो निहनत्येष)',
    'uneasyness (vaikalyam va prayachchhati, वैकल्यं वा प्रयच्छति)',
    'antarayamyate griva (अन्तरायम्यते ग्रीवा)',
    'stiffed neck (manya cha stabhyate bhrishama, मन्या च स्तभ्यते भृशम)',
    'damtanam damshanam (दंतानां दंशनं)',
    'dribbling (lala, लाला)',
    'prishthakshepa (पृष्ठाक्षेप)',
    'shirograha (शिरोग्रह)',
    'jrimbha (जृम्भा)',
    'vadanasamgashchapya (वदनसंगश्चाप्य)',
    'frothy semen (phenila shukra, फेनिल शुक्र)',
    'watery semen (tanu shukra., तनु शुक्र.)',
    'dry semen (ruksha shukra, रुक्ष शुक्र)',
    'krichchhrena alpa shukra (कृच्छ्रेण अल्प शुक्र)',
    'inable to conceive (garbhasthapana asamartha, गर्भस्थापन असमर्थ)',
    'blue coloured semen (nila shukra, नील शुक्र)',
    'yellow coloured semen (pita shukra, पीत शुक्र)',
    'increased temperature of semen (ati ushna shukra, अति उष्ण शुक्र)',
    'raw smelly semen (puti gamdhi shukra, पूति गंधी शुक्र)',
    'daha limga viniryati shukra (दाह लिंग विनिर्याति शुक्र)',
    'obstruction of urethra (baddha shukra marga, बद्ध शुक्र मार्ग)',
    'extremly sticky semen (ati pichchhila shukra, अति पिच्छील शुक्र)',
    'semen with blood (raktamishrita shukra visarjana, रक्तमिश्रित शुक्र विसर्जन)',
    'baddha shukra marga (बद्ध शुक्र मार्ग)',
    'krichchhrena yati shukra (कृच्छ्रेण याति शुक्र)',
    'grathita shukra (ग्रथित शुक्र)',
    'yada bahum padam cha janum cha tasmina samkochayatyardhe karoti cha (यदा बाहुं पादं च जानूं च तस्मिन संकोचयत्यर्धे करोति च)',
    'disfigurement of nose (vakrikaroti nasastatha, वक्रीकरोती नासास्तथा)',
    'disfigurement of eyebrow (vakrikaroti bhrustatha, वक्रीकरोती भ्रूस्तथा)',
    'vakrikaroti lalatastatha (वक्रीकरोती ललाटस्तथा)',
    'vakrikaroti akshistatha (वक्रीकरोती अक्षीस्तथा)',
    'vakrikaroti hanustatha (वक्रीकरोती हनुस्तथा)',
    'tato vakra  vrajatyasye bhojanam (ततो वक्र  व्रजत्यास्ये भोजनं)',
    'vakranasikam (वक्रनासिकं)',
    'stabdhama netram kathayata: (स्तब्धम नेत्रं कथयत:)',
    'kshavathushcha nigrihyate (क्षवथुश्च निगृह्यते)',
    'dina jihma samutkshapta kala sajjati chasya vaka (दीना जिह्मा समुत्क्षप्ता कला सज्जति चास्य वाक)',
    'dantashchalanti (दन्ताश्चलन्ति)',
    'badhyate shravanom (बाध्यते श्रवणों)',
    'bhidyate svara: (भिद्यते स्वर:)',
    'pada ruka (पाद रुक)',
    'hasta ruka (हस्त रुक)',
    'akshi ruka (अक्षि रुक)',
    'jamghom ruka (जंघों रुक)',
    'shamkha ruka (शंख रुक)',
    'shravana ruka (श्रवण रुक)',
    'gandaruka (गण्डरुक)',
    'ardhe tasminmukhardhe (अर्धे तस्मिन्मुखार्धे)',
    'chest stiffness (hridastambha, हृदस्तंभ)',
    'disease of head (shira roga, शिर रोग)',
    'headache (shira shula, शिर शूल)',
    'heaviness of head (shira gaurava, शिर गौरव)',
    'burping (udgara, उद्गार)',
    'runny nose (pinasa, पिनस)',
    'pricking pain in vagina (yoni toda, योनि तोद)',
    'stiffness (stambha, स्तंभ)',
    'pipilikasripti (पिपिलीकासृप्ति)',
    'hardening (karkashatam, कर्कशतां)',
    'numbness (supti, सुप्ति)',
    'tiredness (ayasa, आयास)',
    'menstrual bleeding with Sound (sashabda artava, सशब्द आर्तव)',
    'menstrual bleeding with pain (savedana artava, सवेदना आर्तव)',
    'frothy menstrual bleeding (saphena artava, सफेन आर्तव)',
    'Diluted menstrual bleeding (tanu artava, तनु आर्तव)',
    'ruksha artava (रुक्ष आर्तव)',
    'burning sensation in vaginal canal (yoni daha, योनि दाह)',
    'yoni paka (योनि पाक)',
    'fever (jvara, ज्वर)',
    'ushnata (उष्णता)',
    'blue coloured menstrual bleeding (nila artava, नील आर्तव)',
    'yellow coloured menstrual bleeding (pita artava, पीत आर्तव)',
    'sita artava (सीत आर्तव)',
    'hot vaginal discharge (ushna yonistrava, उष्ण योनिस्त्राव)',
    'smelly vaginal discharge (kunapa yonistrava, कुणप योनिस्त्राव)',
    'itching in vaginal canal (yonikamdu, योनिकंडू)',
    'stickiness in vaginal canal (yoni pichchhilam, योनि पिच्छीलां)',
    'feeling of coldness in vaginal canal (yoni shaitya, योनि शैत्य)',
    'less pain in vaginal canal (yoni alpa vedana, योनि अल्प वेदना)',
    'whitish menstrual bleeding (pamdu artava, पांडू आर्तव)',
    'sticky menstrual bleeding (pichchhila artava, पिच्छील आर्तव)',
    'whitening of skin (pamdu sharira, पांडू शरीर)',
    'pain in vaginal canal (yoni shula, योनि शूल)',
    'white vaginal discharge (shveta yonistrava, श्वेत योनिस्त्राव)',
    'sticky vaginal discharge (pichchhila yoni strava, पिच्छील योनि स्त्राव)',
    'more bleeding through vagina even in pregnancy (ati pravartate yonyam labdhe garbhe api sasrija, अति प्रवर्तते योन्याम् लब्धे गर्भे आपि सासृजा)',
    'no menstrual bleeding (asrika, असृक)',
    'loss of body mass (karshya, कार्श्य)',
    'discoloration of body (vaivarnya, वैवर्ण्य)',
    'weakness (bhrisham, भृशं)',
    'kamdu (कंडू)',
    'ati narakamkshini (अति नरकांक्षीणि)',
    'shopha (शोफ)',
    'supti (सुप्ति)',
    'ruka (रुक)',
    'back pain (prishtha ruja, पृष्ठ रुजा)',
    'pain in waist (kati ruja, कटी रुजा)',
    'pain in thighs (uru ruja, उरू रुजा)',
    'pain in inguinal region (vamkshana ruja, वंक्षण रुजा)',
    'whitish vaginal discharge (pamdu yonistrava, पांडू योनिस्त्राव)',
    'toda (तोद)',
    'shveta yonistrava (श्वेत योनिस्त्राव)',
    'kaphaj and vataj diseases (kapha vataja roga, कफ वातज रोग)',
    'swelling in vagina (yoni shotha, योनि शोथ)',
    'sparshasahatva (स्पर्शासहत्व)',
    'blue coloured vaginal bleeding (nila asrika yonistrava, नील असृक योनिस्त्राव)',
    'yellow coloured vaginal bleeding (pita asrika yonistrava, पीत असृक योनिस्त्राव)',
    'shroni shula (श्रोणि शुल)',
    'vamkshana shula (वांक्षण शुल)',
    'prishtha shula (पृष्ठ शुल)',
    'jvara (ज्वर)',
    'yoni shula (योनि शूल)',
    'raja: krichchhrena udavrittam vimumchati (रज: कृच्छ्रेण उदावृत्तम् विमुंचती)',
    'artava vimukte tamtkshanam labhate sukham (आर्तव विमुक्ते तंत्क्षणं लभते सुखं)',
    'formation of comb like structure in vagina (yoni karnika utpatti, योनि कर्णिका उत्पत्ती)',
    'repeated fetal death (garbham jatam jatam vinashayet, गर्भम् जातं जातं विनाशयेत्)',
    'vakrayati ananam yonya: (वक्रयति अननं योन्या:)',
    'vataj pain in bones of vaginal canal (yonya: asthi anila artibhi:, योन्या: अस्थि अनिल अर्तिभि:)',
    'vataj pain in muscles of vaginal canal (yonya: mamsa anila artibhi:, योन्या: मांस अनिल अर्तिभि:)',
    'inability to copulate (maithuna ashakta, मैथुन अशक्ता)',
    'pinhole os of cervix of female fetus (garbha sthaya striyam anu dvaram, गर्भ स्थाया स्त्रियां अणु द्वारां)',
    'mala sagna (मल सग्ङ)',
    'mutra sagna (मूत्र सग्ङ)',
    'yonimukha shosha (योनीमुख शोष)',
    'expulsion of semen inserted in vagina with or without pain after 6 or 7 days of copulation (shada-sapta ratradva shukram garbhashayam gatam| sarujam nirujam sraveta, षड-सप्त रात्राद्वा शुक्रम् गर्भाशयं गतं| सरुजम् निरूजम् स्रवेत)',
    'destruction of uterus in female fetus (garbhastha kanya garbhashaya nasha, गर्भस्थ कन्या गर्भाशय नाश)',
    'hatred for males (nara dveshi, नर द्वेषी)',
    'absence of breasts (astani, अस्तनी)',
    'obstructed uterus (garbhashaya vishtambha, गर्भाशय विष्टम्भ)',
    'obstructed cervix (yonimukha vishtambha, योनीमुख विष्टम्भ)',
    'opened cavity of cervical canal (asamvrita mukhi yoni, असंवृत मुखी योनि)',
    'yoni shula (योनि शुल)',
    'dry vaginal discharge (ruksha yonistrava, रुक्ष योनिस्त्राव)',
    'frothy vaginal discharge (phena yonistrava, फेन योनिस्त्राव)',
    'yonimukha mamsotsanna (योनीमुख मांसोत्सन्ना)',
    'pain in joints (parva shula, पर्व शुल)',
    'vamkshana ruja (वंक्षण रुजा)',
    'mild redness in eyes (alpastu rago, अल्पस्तु रागो)',
    'anupadehavamshrcha (अनुपदेहवांश्र्च)',
    'pricking pain in eyes (satoda, सतोद)',
    'breaking like pain in eyes (bheda, भेद)',
    'burning sensation in eyes (sadaho, सदाहो)',
    'intense pain in eyes (atiruja:, अतिरुज:)',
    'more redness in eyes (saraga:, सराग:)',
    'yellowish discharge from eyes (pitopadeha:, पितोपदेह:)',
    'hot tears from eyes (subhrishoshnavahi, सुभृशोष्णवाही)',
    'whitish discharge from eyes (shuklopadeham, शुक्लोपदेहं)',
    'sticky tears discharge from eyes (bahupichchhilashru, बहुपिच्छिलाश्रू)',
    'heaviness in eyes (netra guruta, नेत्र गुरुता)',
    'itching in eyes (sakandu:, सकण्डु:)',
    'all symptoms (sarvani rupani, सर्वानी रुपाणी)',
    'sound in ears (nada, नाद)',
    'pain in ear (atiruka, अतिरुक)',
    'drying of ear wax (karnamalasya shosha:, कर्णमलस्य शोष:)',
    'thin liquid discharge from ear (stravastanushrcha, स्त्रावस्तनुश्र्च)',
    'inability to hear (ashravanam, अश्रवणं)',
    'swelling in ear (shopha:, शोफ:)',
    'redness in ear (sarago, सरागो)',
    'daranam (दरणं)',
    'burning sensation in ear (vidaha:, विदाह:)',
    'yellow liquid discharge from ear containing foul smell (sapitaputishravanam, सपितपुतीश्रवणं)',
    'inability to listen properly (vaishrutya, वैश्रूत्य)',
    'itching in ear (kandu, कण्डु)',
    'stable swelling in one place (sthira shopha, स्थिर शोफ)',
    'greasy white discharge (shuklasnigdhastruti: shleshma, शुक्लस्निग्धस्त्रुती: श्लेष्म)',
    'mild pain (alparuka, अल्परुक)',
    'all symptoms (sarvamni rupani, सर्वांनी रूपाणी)',
    'stravashrcha tatradhikadoshavarna: (स्त्रावश्र्च तत्राधीकदोषवर्ण:)',
    'samsprishya marmanyanilastu murdhni vishvakpathastha: (संस्पृश्य मर्माण्यनिलस्तू मुर्ध्नि विष्वक्पथस्थ:)',
    'kruddha: sa samshoshya kapham tu nasashrimgatakaghranavishoshanam cha (क्रुद्ध: स संशोष्य कफं तु नासाशृंगाटकघ्राणविशोषणं च)',
    'uchchhvasamarge tu kapha: savato rumdhyat (उच्छ्वासमार्गे तू कफ: सवातो रुंध्यात्)',
    'mastuulumgad ghanapitapakva: kapha: stravedesha (मस्तूूलुंगाद् घनपीतपक्व: कफ: स्त्रवेदेष)',
    'dullness of face (vaivarnya, वैवर्ण्य)',
    'foul smelling from nose (daurgamdhya, दौर्गांध्य)',
    'swelling in nose (shvayathu, श्वयथु)',
    'vertigo (bhrama, भ्रम)',
    'blockage in nose due to excess cough. (anahyate yasya, आनह्यते यस्य)',
    'dryness in nose (vishushyate, विशुष्यते)',
    'moist nose (praklidyate, प्रक्लीद्यते)',
    'feels like smoke coming from nose (dhupyati, धुप्यती)',
    'inability to detect smell and taste (na vetti yo gamdharasamshcha, न वेत्ती यो गंधरसांश्च)',
    'burning sensation in nose (sadaha, सदहा)',
    'redness of nose (raga:, राग:)',
    'swelling in nose (shvayathu:, श्वयथु:)',
    'pus formation in nose (sapaka:, सपाक:)',
    'swelling in nose (nasa shvayathum, नासा श्वयथुं)',
    'ghrane tathochchhavasagatim nirudhya mamsastradoshadapi (घ्राणे तथोच्छवासगतिं निरुध्य मांसास्त्रदोषादपी)',
    'bleeding from nose containing pus (ghranat stravedva pittaktamastram, घ्राणात् स्त्रवेद्वा पित्ताक्तमस्त्रं)',
    'bleeding from ears containing pus (shravana pittaktamastram, श्रवणा पित्ताक्तमस्त्रं)',
    'bleeding from mouth containing pus (mukhadva pittaktamastram, मुखाद्वा पित्ताक्तमस्त्रं)',
    'charumshi sapakavamti (चारुंषि सपाकवंती)',
    'burning sensation in nose (daha, दाह)',
    'chest pain (hridaya ruga, हृदय रुग)',
    'pain in urinary bladder (basti ruga, बस्ती रुग)',
    'abdominal pain (kukshi ruga, कुक्षि रुग)',
    'udara ruga (उदर रुग)',
    'back pain (prishtha ruga, पृष्ठ रुग)',
    'parshva ruga (पार्श्व रुग)',
    'bloating (adhmana, आध्मान)',
    'nausea (hrillasa, हृल्लास)',
    'parikartika (परिकार्तिका)',
    'pricking pain (guda toda, गुद तोद)',
    'indigestion (avipaka, अविपाक)',
    'swelling of urinary bladder (basti shotha, बस्ति शोथ)',
    'constipation (varcho apravritti, वर्चो अप्रवृत्ती)',
    'jathare cha gandana (जठरे च गण्डान)',
    'urdhvashcha vayurvihato (ऊर्ध्वश्च वायुर्विहतो)',
    'difficulty in passing stool (krichchhena vina pravritti, कृच्छेण विण प्रवृत्ती)',
    'passing dry stool (shushka vina pravritti, शुष्क विण प्रवृत्ती)',
    'dry body (khara sharira, खर शरीर)',
    'dry body (ruksha sharira, रुक्ष शरीर)',
    'cold body (shaitya, शैत्य)',
    'apanavayu apravritti (अपानवायू अप्रवृत्ती)',
    'urinary obstruction (mutra apravritti, मूत्र अप्रवृत्ती)',
    'constipation (purisha apravritti, पुरिष अप्रवृत्ती)',
    'laziness (klama, क्लम)',
    'pain (daruna pida, दारुण पीडा)',
    'pricking pain (toda, तोद)',
    'gasses (atopa, आटोप)',
    'pain (shula, शूल)',
    'constipation (purisha samga, पुरिष संग)',
    'urdhvavata (उर्ध्ववात)',
    'pain in urinary bladder (basti shula, बस्ति शूल)',
    'pain in penis (upastha shula, उपस्थ शूल)',
    'obstructive urination with pain (mutrakrichha, मूत्रकृछ)',
    'headache (shira shula, शिर शूल)',
    'body bebding (deha vinama, देह विनाम)',
    'vamkshana tanava (वंक्षण तणाव)',
    'manyastambha (मान्यस्तंभ)',
    'neck stiffness (grivastambha, ग्रीवास्तंभ)',
    'head disease (shira roga, शिर रोग)',
    'nose disease (nasa roga, नासा रोग)',
    'eye disease (netra roga, नेत्र रोग)',
    'mouth disease (mukha roga, मुख रोग)',
    'ear disease (karna roga, कर्ण रोग)',
    'heaviness of head (shirogaurava, शिरोगौरव)',
    'disease of eye (netra roga, नेत्र रोग)',
    'runny nose (pinasa, पिनस)',
    'pratishyaya (प्रतिश्याय)',
    'headache (shirashula, शिरशूल)',
    'facial paralysis (ardita, अर्दित)',
    'migraine (ardhavabhedaka, अर्धावभेदक)',
    'feeling of throat fullness (kamtha purna pratiti, कंठ पूर्ण प्रतीती)',
    'feeling of mouth fullness (mukha purna pratita, मुख पूर्ण प्रतीत)',
    'kujana (कूजन)',
    'vayu avarodha (वायू अवरोध)',
    'vataja vikara (वातज विकार)',
    'itching (kamdu, कंडू)',
    'votiligo (kotha, कोठ)',
    'anorexia (aruchi, अरुची)',
    'swelling (shotha, शोथ)',
    'anemia (pamdu, पांडू)',
    'fever (jvara, ज्वर)',
    'skin disease (kushtha, कुष्ठ)',
    'erysipelas (visarpa, विसर्प)',
    'pain in urinary bladder (mutrashaya pida, मूत्राशय पीडा)',
    'anus pain (guda pida, गुद पीडा)',
    'mushkashotha pida (मुष्कशोथ पीडा)',
    'urine obstruction (mutravinigraha, मूत्रविनिग्रह)',
    'shukrashmari (शुक्राश्मरी)',
    'shukrasravana (शुक्रस्रवण)',
    'body pain (amgamarda, अंगमर्द)',
    'tamdra (तंद्रा)',
    'fatigue (shrama, श्रम)',
    'kasharya (काशर्य)',
    'dryness of throat (kamtha shosha, कंठ शोष)',
    'dryness of mouth (mukha shosha, मुख शोष)',
    'chest pain (hridavyatha, हृदव्यथा)',
    'badhirya (बाधिर्य)',
    'hridaroga (हृदरोग)',
    'murchchha (मूर्च्छा)',
    'gulma (गुल्म)',
    'jrimbha (जृम्भा)',
    'amgamarda (अंगमर्द)',
    'akshi jadata (अक्षि जडता)',
    'shira jadata (शिर जडता)',
    'gnashing of teeth (parihrishtadamta:, परीहृष्टदंत:)',
    'astringent in taste (kashayavaktrashrcha, कषायवक्त्रश्र्च)',
    'bitter taste in mouth (katvaktram, कट्वक्त्रं)',
    'sour taste in mouth (amlavaktram, अम्लवक्त्रं)',
    'tastelessness of mouth (virasamvaktram, विरसंवक्त्रं)',
    'warmth in mouth (ushnamvaktram, उष्णंवक्त्रं)',
    'foul smelling from mouth (putivaktram, पुतीवक्त्रं)',
    'saltiness in mouth (lavanam cha vaktram, लवणं च वक्त्रं)',
    'sweetness in mouth (madhurya, माधुर्य)',
    'stickiness in mouth (paichchhilya, पैच्छिल्य)',
    'heaviness in mouth (gurutva, गुरुत्व)',
    'coldness in mouth (shaitya, शैत्य)',
    'constipation (vibaddha, विबद्ध)',
    'cough in mouth (sambaddhayutam kaphena, संबद्धयुतं कफेन)',
    'presence of several tastes in mouth (anaikarasam bhavettu, अनैकरसं भवेत्तू)',
    'normal taste of mouth though refusal to eat (svabhavikam vaktramatharuchishcha, स्वाभाविकं वक्त्रमथारूचिश्च)',
    'itching (kandu, कण्डू)',
    'burning sensation (daha, दाह)',
    'pain (ruga, रुग)',
    'pricking pain (toda, तोद)',
    'ayama (आयाम)',
    'skin becomes blackish (shayava tvaga, शयाव त्वग)',
    'skin becomes reddish (rakta varni tvaga, रक्त वर्णी त्वग)',
    'brownish skin (tamra varni tvaga, ताम्र वर्णी त्वग)',
    'pulsation (sphurana, स्फुरण)',
    'swelling (shvayathu, श्वयथु)',
    'stiffness (stabdhata, स्तब्धता)',
    'kathinata (काठीणता)',
    'severe pain (pida, पीडा)',
    'blackish skin (shyava tvacha, श्याव त्वचा)',
    'brownish skin (tamra tvacha, ताम्र त्वचा)',
    'paka (पाक)',
    'chhinna vata vedana (छिन्न वत वेदना)',
    'vakra samdhi (वक्र संधी)',
    'khamjatva (खंजत्व)',
    'panagutvam (पङगुत्वं)',
    'vein strain (sira ayama, सिरा आयाम)',
    'pain (shula, शूल)',
    'blackish swelling (krishna varni shotha, कृष्ण वर्णी शोथ)',
    'dryness in swelling (shotha rukshata, शोथ रुक्षता)',
    'shotha shyavata (शोथ श्यावता)',
    'sometimes swelling increases (shotha vriddhi, शोथ वृद्धि)',
    'sometimes swelling decreases (shotha hani, शोथ हानि)',
    'dhamanya samkocha (धमन्य संकोच)',
    'anaguli samkocha (अङगुलि संकोच)',
    'samdhi samkocha (संधी संकोच)',
    'amga graha (अंग ग्रह)',
    'pain in body parts (amga ruka, अंग रुक)',
    'amga kumchana (अंग कुंचन)',
    'amga stambhana (अंग स्तंभन)',
    'hates cold thing (shita dvesha, शीत द्वेष)',
    'burning sensation (vidaha, विदाह)',
    'pain (vedana, वेदना)',
    'unconsciousness (murchchha, मूर्च्छा)',
    'sweating (sveda, स्वेद)',
    'thirsty (trishna, तृष्णा)',
    'mada (मद)',
    'vertigo (bhrama, भ्रम)',
    'reddishness in affected area (raga:, राग:)',
    'pain in affected area (bheda, भेद)',
    'dryness in affected area (shosha, शोष)',
    'staimityam (स्तैमित्यं)',
    'heaviness of body (gauravata, गौरवता)',
    'snigdhata (स्निग्धता)',
    'numbness (supti, सुप्ती)',
    'slight pain (mamda vedana, मंद वेदना)',
    'dryness in mouth (shosha, शोष)',
    'hardness in mouth (karkashya, कार्कश्य)',
    'roughness in mouth (raukshyani, रौक्ष्याणी)',
    'pain in different-different regions (chala rujashcha, चला रुजश्च)',
    'face turns black or red (krishnarunam, कृष्णारुणं)',
    'cold liquid discharge from mouth (nishpatanam sashitam, निष्पतनं सशीतं)',
    'momentarily fall of teeth (prastramsana, प्रस्त्रंसन)',
    'shivering of body (spamdana, स्पंदन)',
    'pricking pain (toda, तोद)',
    'pain like breaking of body (bheda:, भेदा:)',
    'more thirst (trishna, तृष्णा)',
    'fever (jvara, ज्वर)',
    'ulcer in mouth (sphotaka, स्फोटक)',
    'burning sensation in palate (taludaha, तालूदाह)',
    'feels like hot air coming from mouth (dhumayanam, धुमायनं)',
    'cracks in lips (chapyavadirnata, चाप्यवदिर्णता)',
    'dizziness (samurchchha, समुर्च्छा)',
    'many pains (vividha rujashcha, विविधा रूजश्च)',
    'varnashcha shuklaarunavarnavarjya: (वर्णाश्च शुक्लअरुणवर्णवर्ज्या:)',
    'itching in mouth (kandu, कण्डु)',
    'heaviness in mouth (gurutvam, गुरुत्वं)',
    'whitish mouth (sita, सित)',
    'vijjalatvam (विज्जलत्वं)',
    'sneho (स्नेहो)',
    'Anorexia (aruchi, अरुची)',
    'heaviness during movement of mouth (jadya, जाड्य)',
    'salivation (kaphaprasekau, कफप्रसेकौ)',
    'nausea (utkalesha, उत्कलेश)',
    'low digestive fire (mamdanalata, मंदानलता)',
    'sleepiness (tamdra, तंद्रा)',
    'mild pain in organs and mouth (rujashrcha mamda: kaphavaktroroge, रुजश्र्च मंदा: कफवक्त्रोरोगे)',
    'all symptoms (sarvani rupani, सर्वाणि रुपाणी)',
    'dryness of mouth (mukha shosha, मुख शोष)',
    'difficulty in committing (kashta vata pravritti, कष्ट वत प्रवृत्ती)',
    'vomitting with high intensity (prabala vega, प्रबल वेग)',
    'mucous in vomitting (phena yukta, फेन युक्त)',
    'blackish vomitting (krishna varni, कृष्ण वर्णी)',
    'headache (shira vedana, शिर वेदना)',
    'vomitting in less quantity (alpa matra, अल्प मात्रा)',
    'vichchhinna chhardi (विच्छिन्न छर्दी)',
    'vomitting containing more water (tanu chhardi, तनु छर्दी)',
    'vomitting with astringent taste (kashaya rasatmaka chhardi, कषाय रसात्मक छर्दी)',
    'chest pain (hridaya pida, हृदय पीडा)',
    'parshva pida (पार्श्व पीडा)',
    'nabhi vedana (नाभि वेदना)',
    'coughing (kasa, कास)',
    'soar throat (svarabheda, स्वरभेद)',
    'pricking pain in the body (amga toda, अंग तोद)',
    'uchcha shabdavata udagara (उच्च शब्दवत उदगार)',
    'to faint (murchchha, मूर्च्छा)',
    'thirst (pipasa, पिपास)',
    'burning head (shira samtapa, शिर संताप)',
    'talu samtapa (तालु संताप)',
    'burning eyes (akshi samtapa, अक्षि संताप)',
    'bhrama (भ्रम)',
    'yellow vomiting (pita varni chhardi, पीत वर्णी छर्दी)',
    'greenish vomiting (harita varni chhardi, हरित वर्णी छर्दी)',
    'bitter vomiting (tiktarasatmaka chhardi, तिक्तरसात्मक छर्दी)',
    'dhumra varni chhardi (धुम्र वर्णी छर्दी)',
    'burning sensation (sadaha chhardi, सदाह छर्दी)',
    'Laziness (tandra, तन्द्रा)',
    'sweetness of mouth (asya madhurya, आस्य माधुर्य)',
    'dribbling (kapha praseka, कफ प्रसेक)',
    'feeling of stomach fullness (samtosha, संतोष)',
    'nidra (निद्रा)',
    'anorexia (aruchi, अरुची)',
    'body heaviness (gauravata, गौरवता)',
    'vomiting with mucous (snigdha chhardi, स्निग्ध छर्दी)',
    'ghana chhardi (घन छर्दी)',
    'sweet vomiting (madhura chhardi, मधुर छर्दी)',
    'vishuddha kapha yukta chhardi (विशुद्ध कफ युक्त छर्दी)',
    'lomaharsha (लोमहर्ष)',
    'vomiting with less efforts (alpa ruja, अल्प रुज)',
    'abdominal pain (udara shula, उदर शूल)',
    'indigestion (avipaka, अविपाक)',
    'thirst (trishna, तृष्णा)',
    'shvasa (श्वास)',
    'to faint (moha, मोह)',
    'acidic vomiting (amla chhardi, अम्ल छर्दी)',
    'salty vommitting (lavana rasatmaka  chhardi, लवण रसात्मक  छर्दी)',
    'bluish vomitting (nila chhardi, निल छर्दी)',
    'samdra chhardi (सांद्र छर्दी)',
    'blood in vomitting (ushna rakta yukta chhardi, उष्ण रक्त युक्त छर्दी)',
    'vinavarni chhardi (विणवर्णी छर्दी)',
    'mutra varni chhardi (मूत्र वर्णी छर्दी)',
    'vina gamdhi chhardi (विण गंधि छर्दी)',
    'mutra gamdhi chhardi (मूत्र गंधि छर्दी)',
    'thirsty (trishna, तृष्णा)',
    'hiccups (hikka, हिक्का)',
    'excessive pain in head (bhrishartishulam, भृशार्तीशुलम्)',
    'fluttering in head (sphuratiha, स्फुरतीह)',
    'burning sensation and pain in head (sadaharti, सदाहार्ती)',
    'feeling of weight putted on head (guru syat, गुरु स्यात्)',
    'all symptoms (sarvaistridosham, सर्वैस्त्रिदोषं)',
    'itching (kamdu, कंडु)',
    'foul smell (daurgamdhya, दौर्गंध्य)',
    'pricking pain (todarti, तोदार्ती)',
    'faecal matter mixes in water (vijjala mamam, विज्जल मामं)',
    'undigested faecal matter (viplutama, विप्लुतम)',
    'thin faecal matter (avasadi, अवसादी)',
    'dry faecal matter (ruksha, रुक्ष)',
    'faecal matter sinks in water (drava, द्रव)',
    'foul smelling of faecal matter (amagamdhi, आमगंधी)',
    'faecal matter comes out along with loud or slow sound (shabdamashabdam va, शब्दमशब्दं वा)',
    'stool comes out along with obstruction of urine and gases (vibaddhamutravatamatisaryate purisham, विबद्धमुत्रवातमतीसार्यते पुरिषम्)',
    'obstructed gases causes sound and pain in intestine (vayushchanta: koshthe sashabdashula vibaddha, वायूश्च्आन्त: कोष्ठे सशब्दशुल विबद्ध)',
    'vayustiryaka charati (वायुस्तिर्यक चरती)',
    'binded stool (vibaddhama, विबद्धम)',
    'slow sound during discharge of stool (alpapalpam sashabda, अल्पापल्पं सशब्द)',
    'pain during discharge of stool (sashula mala, सशूल मल)',
    'stool with froath (saphena, सफेन)',
    'sticky stools (pichchha, पिच्छा)',
    'parikartikam (परीकर्तिकं)',
    'goosebumps during discharge of stool (hrishtaroma, हृष्टरोमा)',
    'breathlessness during discharge of stool (vini: shvasan, विनी: श्वसञ्)',
    'dryness of mouth (shushkamukha:, शुष्कमुख:)',
    'pain in hip region (kati shula, कटी शूल)',
    'pain in thighs (uru shula, उरू शूल)',
    'pain in pelvic region (trikashula, त्रिकशूल)',
    'pain in knee region (janu shula, जानू शूल)',
    'pain in back (prishtha shula, पृष्ठ शूल)',
    'pain in lateral side of chest region (parshva shula, पार्श्व शूल)',
    'rupture of anal region (bhrashtaguda, भ्रष्टगुद)',
    'muhurmuhurvigrathitamupaveshyate purisha (मुहुर्मुहुर्विग्रथितमुपवेश्यते पुरिष)',
    'yellowishness of stool (haridram purisham, हारिद्रं पूरिषं)',
    'greenish stool (haritam purisham, हरीतं पुरिषं)',
    'bluish stool (nilam purisham, निलं पुरिषं)',
    'blackish stool (krishnam purisham, कृष्णं पुरिषं)',
    'stool containing blood (raktapittopahitam, रक्तपित्तोपहितं)',
    'foul smelling of stool (atidurgandhamatisaryate, अतिदुर्गन्धमतिसार्यते)',
    'thirsty (trishna, तृष्णा)',
    'burning sensation (daha, दाह)',
    'sweating (sveda, स्वेद)',
    'vertigo (murchchha, मूर्च्छा)',
    'stomach ache (udara shula, उदर शूल)',
    'burning in anal region (guda daha, गुद दाह)',
    'guda paka (गुद पाक)',
    'snigdham purisham (स्निग्धं पुरिषं)',
    'whitish stool (shvetam purisham, श्वेतं पुरिषं)',
    'sticky stools (pichchhila purisham, पिच्छिल पुरिषं)',
    'tamtum purisham (तंतुं पुरिषं)',
    'undigested faecal matter (amam purisham, आमं पुरिषं)',
    'heavy stool (guru purisham, गुरु पुरिषं)',
    'foul smelling stool (durgamdha purisham, दुर्गंध पुरिषं)',
    'shleshmopahitam (श्लेष्मोपहीतं)',
    'stomach ache (udarashula, उदरशूल)',
    'frequent passage of stool (alpalpambhikshnamatisaryate sapravahikam, अल्पाल्पंभिक्ष्णमतिसार्यते सप्रवाहिकं)',
    'heavyness in stomach region (guru udara, गुरु उदर)',
    'heavyness in anal region (guru guda, गुरु गुद)',
    'heavyness in urinary bladder (guru basti, गुरु बस्ती)',
    'heavyness in inguinal region (guru vamkshana, गुरु वंक्षण)',
    'kriteapyakrita samjna: (कृतेअप्यकृत संज्ञ:)',
    'goosebumps (salomaharsha:, सलोमहर्ष:)',
    'salivation (sotklesho, सोत्क्लेशो)',
    'excessive sleep (nidra, निद्रा)',
    'sluggishness (alasya, आलस्य)',
    'exhaustion (sadana, सदन)',
    'refusal of food (annadvesha, अन्नद्वेष)',
    'pakva shonitabham (पक्व शोणीताभं)',
    'stool like piece of liver (yakritkhandopamam, यकृत्खण्डोपमं)',
    'medomamsodakasannikasham (मेदोमांसोदकसन्निकाशं)',
    'stool like curd (dadhi sama purisha, दधी सम पूरिष)',
    'stool like ghee (ghrita sama purisha, घृत सम पुरीष)',
    'majja sama mala (मज्जा सम मल)',
    'stool like oil (taila sama mala, तैल सम मल)',
    'stool like fats (vasa sama mala, वसा सम मल)',
    'stool like milk (kshira sama mala, क्षीर सम मल)',
    'vesavara sama mala (वेसवार सम मल)',
    'more bluish stool (ati nila, अति नील)',
    'more reddish stool (ati rakta, अति रक्त)',
    'more blackish stool (ati krishna, अति कृष्ण)',
    'stool like clear water (udakamivachchham, उदकमिवाच्छं)',
    'punarmechakabhama (पूनर्मेचकाभम)',
    'atisnigdha (अतिस्निग्ध)',
    'greenish stool (harita purisham, हरित पुरिषं)',
    'bluish stool (nila purisham, नील पुरिषं)',
    'kashaya purisham (कषाय पुरिषं)',
    'karbura (कर्बुर)',
    'avilam (आविलं)',
    'sticky stool (pichchhilam, पीच्छिलं)',
    'tamtuma purisham (तंतुम पुरिषं)',
    'undigested stool (amam purisham, आमं पुरिषं)',
    'shiny stool (chamdrakopagatama, चंद्रकोपगतम)',
    'atikunapa gamdhi (अतिकुणप गंधी)',
    'pus like foul smell of stool (putipuyagamdhi, पुतीपुयगंधी)',
    'stool smelling like fish (matsyagamdhi, मत्स्यगंधी)',
    'makshikakramtam (मक्षिकाक्रांतं)',
    'rotten stool (kuthita purisham, कुथित पुरिषं)',
    'bahudhatustrava (बहुधातूस्त्राव)',
    'less stool (alpa purisham, अल्प पुरिषं)',
    'more thirst (trishna, तृष्णा)',
    'fever (jvara, ज्वर)',
    'bhrama (भ्रम)',
    'asthma (tamakashvasa, तमकश्वास)',
    'hiccups (hikka, हिक्का)',
    'breathlessness (shvasanubamdha, श्वासानुबंध)',
    'sometimes less or more stomach ache (ativedanamavedanam, अतिवेदनमवेदनं)',
    'pakva gudam (पक्व गुदं)',
    'patita gulavalimam (पतीत गुलवलिमं)',
    'widening of anus (mukta nala, मुक्त नाल)',
    'decrease in strength (atikshina bala, अतिक्षीण बल)',
    'atikshina mamsa (अतिक्षीण मांस)',
    'low blood (atikshina shonita, अतिक्षीण शोणीत)',
    'pain in all joints and bones (sarvaparvasthishulina, सर्वपर्वास्थिशुलीन)',
    'anorexia (arochaka, अरोचक)',
    'arati (अरती)',
    'patter (pralapa, प्रलाप)',
    'unconsciousness (sammoha, संमोह)',
    'sudden cure of the disease (sahasoparatavikarama, सहसोपरतविकारम)',
    'insomnia (nidranasha, निद्रानाश)',
    'Dizziness (shirobhrama, शिरोभ्रम)',
    'Xerostomia (mukha shushkata, मुख शुष्कता)',
    'mukha vairasya (मुख वैरस्य)',
    'tiktasyata (तिक्तास्यता)',
    'burning sensation in head region (shirodaha, शिरोदाह)',
    'desire for cold food (shitechchha, शीतेच्छा)',
    'murchchha (मूर्च्छा)',
    'yellowishness of eye (netra pitata, नेत्र पितता)',
    'yellowishness of urine (mutra pitata, मूत्र पिताता)',
    'yellowishness of stool (varcha pitata, वर्च पितता)',
    'anorexia (aruchi, अरुची)',
    'adhmana (आध्मान)',
    'dribble (kaphapraseka, कफप्रसेक)',
    'pain in nose and pricking pain (ghranartitodau, घ्रणार्तीतोदौ)',
    'sneezing (kshavathurjalabha:, क्षवथूर्जलाभ:)',
    'water like liquid discharge from nose (stravoanilat, स्त्रावोअनीलात्)',
    'headache and sore throat (sasvaramurdharoga:, सस्वरमुर्धरोग:)',
    'pus formation in front portion of nose (nasagrapaka, नासाग्रपाक)',
    'fever (jvara, ज्वर)',
    'dryness of mouth (vaktrashosha, वक्त्रशोष)',
    'thirst (trishna, तृष्णा)',
    'discharge of hot yellow liquid from nose (ushnapitastravanani, उष्णपीतस्त्रवणानी)',
    'cough (kasa, कास)',
    'anorexia (aruchi, अरुची)',
    'thick mucous discharge (stravaghanapraseka:, स्त्रावघनप्रसेका:)',
    'itching in nose (strotasi chapi kandu:, स्त्रोतसी चापी कण्डू:)',
    'all symptoms (sarvani rupani, सर्वाणी रूपाणी)',
    'intense pain (tivrarujeatidu:khe, तीव्ररुजेअतिदु:खे)',
    'injury like pain in nose (rodhabhighata, रोधाभीघात)',
    'watery discharge from nose (strava, स्त्राव)',
    'dryness in nose (shosha, शोष)',
    'pus formation in nose (pakairghranam, पाकैर्घ्राणं)',
    'inability to smell (yashcha na vetti gamdham, यश्च न वेत्ति गंधम्)',
    'durgamdhi chasyam (दुर्गंधी चास्यं)',
    'frequent cold (bahusha: prakopi dushtapratishyaya, बहुश: प्रकोपी दुष्टप्रतिश्याय)',
    'vertigo (bhrama, भ्रम)',
    'burning sensation (daha, दाह)',
    'feeling thirsty (pipasa, पिपासा)',
    'pricking pain (nistoda, निस्तोद)',
    'stomache (shula, शूल)',
    'bodyache (amgamarda, अंगमर्द)',
    'shivering (kampa, कम्प)',
    'fever (jvara, ज्वर)',
    'bronchial asthama (tamaka shvasa, तमक श्वास)',
    'coughing (kasa, कास)',
    'pain in bones and joints region (asthisamdhibheda, अस्थिसंधिभेद)',
    'vivarna (विवर्ण)',
    'vomiting (vamana, वमन)',
    'arochaka (अरोचक)',
    'indigestion (avipaka, अविपाक)',
    'chakshushorakulatvama (चक्षुषोराकुलत्वम)',
    'shvagamanama (श्वागमानम)',
    'tingling (pipalikasa, पिपलिकास)',
    'visarpati sovakasha:shyavarunabhasa: (विसर्पती सोवकाश:श्यावारुणाभास:)',
    'visarpati sovakasha:shvayathumana (विसर्पती सोवकाश:श्वयथुमान)',
    'nistoda (निस्तोद)',
    'bhedashula (भेदशूल)',
    'ayama (आयाम)',
    'samkocha (संकोच)',
    'harsha (हर्ष)',
    'sphuranairatimatram prapidyate (स्फुरणैरतिमात्रं प्रपिड्यते)',
    'shighrabhadai: sphotakaistanubhirarunabhai: (शीघ्रभदै: स्फोटकैस्तनुभीररुणाभै:)',
    'shyavairvatanuvishadarunalpastravai: (श्यावैर्वातनुविशदारुणाल्पास्त्रावै:)',
    'obstruction in urine and stool (vibaddhavatamutrapurishcha, विबद्धवातमूत्रपुरिश्च)',
    'thirsty (trishna, तृष्णा)',
    'unconsciousness (murchchha, मूर्च्छा)',
    'vomiting (chhardi, छर्दी)',
    'anorexia (aruchi, अरुचि)',
    'bodyach (amgabheda, अंगभेद)',
    'sweating (sveda, स्वेद)',
    'more burning (atimatramantadaha, अतिमात्रमन्तदाह)',
    'pralapa (प्रलाप)',
    'headache (shiro:ruka, शिरो:रुक)',
    'insomnia (svapnama, स्वप्नम)',
    'dizziness (atirbhrama, अतिर्भ्रम)',
    'shitavatavaritarshotimatram (शीतवातवारितर्षोतिमात्रं)',
    'greenishness of eyes (haritanetra, हरितनेत्र)',
    'greenishness of urine (haritamutra, हरितमूत्र)',
    'greenishness of stool (haritavarchastvam, हरितवर्चस्त्वं)',
    'yellowishness of eyes (haridranetra, हारिद्रनेत्र)',
    'yellowishness of urine (haridramutra, हारिद्रमूत्र)',
    'yellowishness of stool (haridravarchastvam, हारिद्रवर्चस्त्वं)',
    'haritarupadarshanam (हरितरूपदर्शनं)',
    'haridrarupadarshanam (हारिद्ररूपदर्शनं)',
    'visarponusarpati sovakashastamra  varnanamanyatamam pushyati (विसर्पोनुसर्पति सोवकाशस्ताम्र  वर्णानामन्यतमं पुष्यति)',
    'visarponusarpati sovakashaharita varnanamanyatamam pushyati (विसर्पोनुसर्पति सोवकाशहरित वर्णानामन्यतमं पुष्यति)',
    'visarponusarpati sovakashaharidra varnanamanyatamam pushyati (विसर्पोनुसर्पति सोवकाशहारिद्र वर्णानामन्यतमं पुष्यति)',
    'visarponusarpati sovakashanila varnanamanyatamam pushyati (विसर्पोनुसर्पति सोवकाशनील वर्णानामन्यतमं पुष्यति)',
    'visarponusarpati sovakashakrishna varnanamanyatamam pushyati (विसर्पोनुसर्पति सोवकाशकृष्ण वर्णानामन्यतमं पुष्यति)',
    'visarponusarpati sovakasharaktanam varnanamanyatamam pushyati (विसर्पोनुसर्पति सोवकाशरक्तानां वर्णानामन्यतमं पुष्यति)',
    'freezing cold (shitaka:, शीतक:)',
    'cold fever (shitajvaro, शीतज्वरो)',
    'heaviness of body (gauravam, गौरवं)',
    'nidra (निद्रा)',
    'tandra (तन्द्रा)',
    'aruchi (अरुची)',
    'madhurasyatvama (मधुरास्यत्वम)',
    'asyopalepo (आस्योपलेपो)',
    'nishthivika (निष्ठिविका)',
    'alasya (आलस्य)',
    'staimityam (स्तैमित्यं)',
    'agninasho (अग्निनाशो)',
    'daurbalya (दौर्बल्य)',
    'visarponusarpati sovakasha:shvavathumana (विसर्पोनुसर्पति सोवकाश:श्ववथुमान)',
    'pandurnatirakta: (पाण्डूर्नातिरक्त:)',
    'snehasu (स्नेहसु)',
    'atistambha (अतिस्तम्भ)',
    'gauravairavanitolpavedanah (गौरवैरवनितोल्पवेदनः)',
    'krichchhrapakai (कृच्छ्रपाकै)',
    'chirakari (चिरकारी)',
    'abhirbahulatvagupalepai: (अभिर्बहुलत्वगुपलेपै:)',
    'sphotai:shvetapandubhiranubadhyate (स्फोटै:श्वेतपाण्डुभिरनुबध्यते)',
    'prabhinastu shvetam stravati (प्रभिनस्तु श्वेतं स्त्रवति)',
    'prabhinastu pichchhila stravati (प्रभिनस्तु पिच्छिल स्त्रवति)',
    'prabhinastu tamtuma stravati (प्रभिनस्तु तंतुम स्त्रवति)',
    'prabhinastu madhdanama stravati (प्रभिनस्तु मध्दनम स्त्रवति)',
    'prabhinastu anubadhdam stravati (प्रभिनस्तु अनुबध्दं स्त्रवति)',
    'prabhinastu snigdhama stravati (प्रभिनस्तु स्निग्धम स्त्रवति)',
    'urdhvam cha gurubhi:sthirairjalavatatai (ऊर्ध्वं च गुरुभि:स्थिरैर्जालावततै)',
    'snigdhairbahulatvagupalepaivranairenubadhyateanushamgi cha bhavati (स्निग्धैर्बहुलत्वगुपलेपैव्रनैरेनुबध्यतेअनुषंगी च भवति)',
    'whitishness of nail (shvetanakha, श्वेतनख)',
    'whitishness of eyes (shvetanayana, श्वेतनयन)',
    'whitishness of mouth (shvetavadana, श्वेतवदन)',
    'whitishness of skin (shvetatvaka, श्वेतत्वक)',
    'whitishness of urine (shvetamutra, श्वेतमूत्र)',
    'whitishness of stool (shvetavarchasva, श्वेतवर्चस्व)',
    'tadupatapadatura:  sarvashariramagamrairivakiryamanam manyate (तदुपतापादातुर:  सर्वशरीरमगांरैरिवकिर्यामाणं मन्यते)',
    'atisara (अतिसार)',
    'to faint (murchchha, मूर्च्छा)',
    'moha (मोह)',
    'bronchial asthama (tamakashvasa, तमकश्वास)',
    'asthisamdhibheda (अस्थिसंधिभेद)',
    'indigation (avipaka, अविपाक)',
    'amga bhedadibhishchabhibhuyate (अंग भेदादिभिश्चाभिभूयते)',
    'visarponusarpati sovakasha: shamtaamgara prakashotirakto va bhavati (विसर्पोनुसर्पति सोवकाश: शांताअंगार प्रकाशोतिरक्तो वा भवति)',
    'agnidagdhaprakaraishcha sphotairupachiyate (अग्निदग्धप्रकारैश्च स्फोटैरूपचीयते)',
    'shighragatvadasveva marmanusari bhavati (शीघ्रगत्वादास्वेव मर्मानुसारी भवति)',
    'hiccoughs (hikka, हिक्का)',
    'breath (shvasa, श्वास)',
    'nashayati nidra (नाशयति निद्रा)',
    'nashtanidra:pramudhasamjno (नष्टनिद्रा:प्रमुढसंज्ञो)',
    'vyathitacheta na kvachana sukhamupalabhate (व्यथितचेता न क्वचन सुखमुपलभते)',
    'aratiparita:sthanadasanachchhayyam (अरतीपरित:स्थानादासनाच्छय्यां)',
    'krantumichchhati klishtabhuyishthashchashu nidram bhajati (क्रान्तुमिच्छति क्लिष्टभूयिष्ठश्चाशु निद्रां भजति)',
    'durbalom (दुर्बलों)',
    'cold fever (shitajvara:, शीतज्वर:)',
    'heaviness of head (shirogurutvam, शिरोगुरुत्वं)',
    'burning sensation (daha:, दाह:)',
    'staimityama (स्तैमित्यम)',
    'amgavasadanam (अंगावसदनं)',
    'moho (मोहो)',
    'annadvesha (अन्नाद्वेष)',
    'pralapo (प्रलापो)',
    'daurbalyama (दौर्बल्यम)',
    'asthibhedo (अस्थिभेदो)',
    'murchchha (मूर्च्छा)',
    'thirst (pipasa, पिपासा)',
    'srotasam pralepo (स्रोतसां प्रलेपो)',
    'jadyamindriyanam (जाड्यमिन्द्रियाणां)',
    'prayopaveshanama (प्रायोपवेशनम)',
    'amgavikshepa (अंगविक्षेप)',
    'amgamarda (अंगमर्द)',
    'arati (अरति)',
    'rautsukyam (रौत्सुक्यं)',
    'visarpati sovakasho raktapidakavakirna (विसर्पति सोवकाशो रक्तपिडकावकीर्ण)',
    'visarpati sovakasho pitapidakavakirna (विसर्पति सोवकाशो पीतपिडकावकीर्ण)',
    'visarpati sovakasho pandupidakavakirna (विसर्पति सोवकाशो पाण्डुपिडकावकीर्ण)',
    'iva mechakabha: (इव मेचकाभ:)',
    'snigdho (स्निग्धो)',
    'bahushma (बहुष्मा)',
    'guru: (गुरू:)',
    'stimitavedana: (स्तिमितवेदन:)',
    'shvayathumana (श्वयथुमान)',
    'gambhirapako (गंभीरपाको)',
    'nirastrava: (निरस्त्राव:)',
    'svinnaklinaputimamsatvaka (स्विन्नक्लिनपुतिमांसत्वक)',
    'putimamsatvaka (पुतिमांसत्वक)',
    'kramenalparuka (क्रमेणाल्परुक)',
    'paramrishtovadiryate kardama ivavapiditoamtaram (परामृष्टोवदिर्यते कर्दम इवावपीडितोअंतरं)',
    'prayachchhutyupaklinaputimamsatyagi (प्रयच्छूत्युपक्लिनपुतिमांसत्यागी)',
    'sirasnayusamdarshi (सिरास्नायुसंदर्शी)',
    'kunapagandhi cha bhavati (कुणपगन्धी च भवति)',
    'samjnasmritihamta cha (संज्ञास्मृतीहंता च)',
    'kaphashaye samjanayati shleshmanamanekadha bhindana kramena gramthimala krichchhra paka  sadhyana (कफशये संजनयती श्लेष्मानमनेकधा भिन्दन क्रमेण ग्रंथिमाला कृच्छ्र पाक  साध्यान)',
    'tivrarujanam (तीव्ररुजानं)',
    'sthulanamanunam va (स्थूलानामणुनां वा)',
    'dirghavrittaraktana (दीर्घवृत्तरक्ताना)',
    'jamgha glani (जंघा ग्लानि)',
    'uru glani (उरू ग्लानि)',
    'shashvata jamgha daha (शाश्वत जंघा दाह)',
    'shashvata uru daha (शाश्वत उरू दाह)',
    'shashvata jamgha vedana (शाश्वत जंघा वेदना)',
    'shashvata uru vedana (शाश्वत उरू वेदना)',
    'increase in pain in lower limbs after touching the ground (padam vyathate nyastam, पदं व्यथते न्यस्तं)',
    'shita sparsham na vetti (शीत स्पर्शम् न वेत्ती)',
    'inability to stand up (samsthane na ishvarah, संस्थाने न ईश्वरः)',
    'inability to stand for very long (pidane na ishvarah, पीडने न ईश्वरः)',
    'inability to walk (gatyam na ishvarah, गत्यां न ईश्वरः)',
    'unable to move lower limbs (chalane na ishvarah, चालने न ईश्वरः)',
    'anyaneyau padau manyate (अन्यनेयौ पादौ मन्यते)',
    'sambhagnavuru padau manyate (संभग्नावूरू पादौ मन्यते)',
    'burning sensation (daha, दाह)',
    'pain (vedana, वेदना)',
    'pricking pain (toda, तोद)',
    'heart pain (hritashula, हृतशूल)',
    'pain in lateral side of chest region (parshva shula, पार्श्व शूल)',
    'chest pain (ura:shula, उर:शूल)',
    'pain in head region (shira:shula, शिर:शूल)',
    'dryness in chest (shushka ura, शुष्क उर)',
    'sore throat (shushka kamtha, शुष्क कंठ)',
    'dryness of mouth (shushka vaktra, शुष्क वक्त्र)',
    'svarabheda (स्वरभेद)',
    'svara bhrishama (स्वर भृशम)',
    'goosebumps (lomaharsha, लोमहर्ष)',
    'svara nirghosha (स्वर निर्घोष)',
    'dainya (दैन्य)',
    'kshobha (क्षोभ)',
    'unconciousness (moha, मोह)',
    'dry cough (shushka kasa, शुष्क कास)',
    'kaफ़ shushkam  krichchhanmuktvaalpatam vrajeta (कफ़ शुष्कं  कृच्छान्मूक्त्वाअल्पतां व्रजेत)',
    'jirneanne  vegavanmaruto bhaveta (जीर्णेअन्ने  वेगवान्मारुतो भवेत)',
    'weakness in body (sharira daurbalya, शरीर दौर्बल्य)',
    'pitanishthivana (पीतनिष्ठीवन)',
    'yellowishness of eyes (pita akshitvam, पीत अक्षीत्वं)',
    'tikta asyatvam (तिक्त आस्यत्वं)',
    'svaramaya : (स्वरामय :)',
    'urodhumayanam (उरोधुमायनं)',
    'thirsty (trishna, तृष्णा)',
    'burning sensation (daha, दाह)',
    'Anorexia (aruchi, अरुची)',
    'vertigo (bhrama, भ्रम)',
    'pratatam kasasamanashcha (प्रततं काससमानश्च)',
    'jyotishiva  cha pashyati (ज्योतीषीव  च पश्यति)',
    'shleshmana pittasamsrishta nishthivati (श्लेष्माण पित्तसंसृष्ट निष्ठीवती)',
    'agnimamdya (अग्निमांद्य)',
    'anorexia (aruchi, अरुची)',
    'vomiting (chchhardi, च्छर्दि)',
    'runny nose (pinasa, पिनस)',
    'nausea (sotklesho, सोत्क्लेशो)',
    'heaviness of body (gaurava, गौरव)',
    'asya madhurya (आस्य माधुर्य)',
    'sharira kledasam (शरीर क्लेदसं)',
    'exhaustion (sadana, सदन)',
    'bahalam madhuram nishthivati  kaफ़ (बहलं मधुरं निष्ठीवती  कफ़)',
    'snigdha nishthivati  kaफ़ (स्निग्ध निष्ठीवती  कफ़)',
    'ghanam nishthivati kaफ़ (घनं निष्ठीवती कफ़)',
    'kasamano hyarug vaksha: sampurnamiva manyate (कासमानो ह्यरुग् वक्ष: सम्पूर्णमिव मन्यते)',
    'intially dry cough present (sa purvamma kasate shushkama, स पूर्वंम कासते शुष्कम)',
    'shthiveta sashonitam (ष्ठिवेत सशोणितम्)',
    'A lot of pain in the throat (kamthena rujaatyartha, कंठेन रुजाअत्यर्थ)',
    'chest pain (viruganeva cha ura, विरुगणेव च उर)',
    'pricking pain in the body (suchibhiriva tikshnabhistudyamanena  shulina, सूचीभिरिव तीक्ष्णाभिस्तुद्यमानेन  शूलिना)',
    'duhkhasparshena  shulena (दुःखस्पर्शेन  शूलेन)',
    'bhedapida (भेदपीडा)',
    'abhitapa (अभिताप)',
    'parvabheda (पर्वभेद)',
    'fever (jvara, ज्वर)',
    'Dysponea (shvasa, श्वास)',
    'vaisvaryapidita: (वैस्वर्यपीडित:)',
    'paravata ivakujan kasavegatkshatodvabhavat (पारावत इवाकूजन् कासवेगात्क्षतोद्वभवात्)',
    'durgamndha shthivet kapham (दूर्गंन्ध ष्ठिवेत् कफम्)',
    'haritam shthivet kapham (हरीतं ष्ठिवेत् कफम्)',
    'rakta shthivet kapham (रक्त ष्ठिवेत् कफम्)',
    'shthivet  puyopamam  kapham (ष्ठिवेत्  पूयोपमं  कफम्)',
    'sthanadutkasamanashcha  hridayam manyate chyutam (स्थानादुत्कसमानश्च  हृदयं मन्यते च्युतम्)',
    'akasmata ushna (अकस्मात उष्ण)',
    'akasmata shita (अकस्मात शीत)',
    'bahyashi durbala (बह्यशी दुर्बल)',
    'lean body (krisha:, कृश:)',
    'snigdhachchhamukha (स्निग्धाच्छमुख)',
    'snigdhachchhavarna (स्निग्धाच्छवर्ण)',
    'snigdhachchhatvak (स्निग्धाच्छत्वक्)',
    'Eyes look attractive (shrimaddarshanalochana:, श्रीमद्दर्शनलोचन:)',
    'soles of the palm and feet remain oily (panipadatalai: shlakshna:, पाणिपादतलै: श्लक्ष्ण:)',
    'satatasuyako ghrini (सततासूयको घृणी)',
    'jvaro mishrakritistasya (ज्वरो मिश्राकृतिस्तस्य)',
    'pain in lateral side of chest region (parshvaruk, पार्श्वरुक्)',
    'bhinnasamhatavarchyastvam (भिन्नसंहतवर्च्यस्त्वं)',
    'svarabhedoanimittata: (स्वरभेदोअनिमित्तत:)',
    'sleep (nidra, निद्रा)',
    'lethargy (tamdra, तंद्रा)',
    'fatigue (klama, क्लम)',
    'burning sensation (daha, दाह)',
    'sapakam (सपाकं)',
    'goosebumps (lomaharshanam, लोमहर्षणम्)',
    'swelling (shopham, शोफं)',
    'diarrhoea (atisara, अतिसार)',
    'fever (jvara, ज्वर)',
    'hiccup (hikka, हिक्का)',
    'damtaharsha (दंतहर्ष)',
    'sore throat (galagraham, गलग्रहम्)',
    'foamy vomit (phenavamya, फेनवम्य)',
    'anorexia (aruchi, अरुची)',
    'asthma (shvasa, श्वास)',
    'convulsion (murchchha, मूर्च्छा)',
    'thirst (trishna, तृष्णा)',
    'moha (मोह)',
    'sensitivity of teeth (damtaharsha, दंतहर्ष)',
    'dribble (praseka, प्रसेक)',
    'vomiting (vamana, वमन)',
    'skin discolouration (vaivarnya, वैवर्ण्य)',
    'dizzeness (bhrama, भ्रम)',
    'tremor (vepathu, वेपथु)',
    'yawing (jrimbha, जृम्भा)',
    'tingling (chimachimayana, चिमचीमायन)',
    'mamdala (मंडल)',
    'itching (kamdu, कंडू)',
    'shvayathu (श्वयथु)',
    'kotha (कोठ)',
    'vomiting (chhardi, छर्दी)',
    'body pain (amgashula, अंगशूल)',
    'niladinam darshanam (नीलादिनां दर्शनं)',
    'tama darshanam (तम दर्शनं)',
    'bhanga:skamdhasya (भङ्ग:स्कंधस्य)',
    'death (mrityu, मृत्यू)',
    'arati (अरती)',
    'galagraha (गलग्रह)',
    'foam from the mouth (mukhadvare phena, मुखद्वारे फेन)',
    'cough (kasa, कास)',
    'vomiting (vamathu, वमथु)',
    'burninig sensation (daha, दाह)',
    'tama darshana (तम दर्शन)',
    'dribble (lalastrava, लालास्त्राव)',
    'oshtha chimachimayana (ओष्ठ चिमचिमायन)',
    'jivha shuna (जिव्हा शूना)',
    'heaviness of tongue (jivha jada, जिव्हा जडा)',
    'jivha vivarnacha (जिव्हा विवर्णाच)',
    'hanustambha (हनुस्तंभ)',
    'burning sensation in mouth (asya daha, आस्य दाह)',
    'asyalala (आस्यलाला)',
    'galavikara: (गलविकार:)',
    'vaivarnyam (वैवर्ण्यं)',
    'sweating (sveda, स्वेद)',
    'fatigue (sadana, सदन)',
    'nausea (utkleda, उत्क्लेद)',
    'hridayoparodho (हृदयोपरोधो)',
    'bimdushataishchiyate changam (बिंदुशतैश्चीयते चाङ्गम्)',
    'mada (मद)',
    'daurbalya (दौर्बल्य)',
    'kurcho vishiryate (कूर्चो विशीर्यते)',
    'damta shopha (दंत शोफ)',
    'oshtha shopha (ओष्ठ शोफ)',
    'mamsa shophashrcha (मांस शोफश्र्च)',
    'hair fall (keshachyutih, केशच्युतिः)',
    'shiroruga (शिरोरुग)',
    'shirogramthayashrcha (शिरोग्रंथयश्र्च)',
    'burninig sensation in eyes (akshidaha, अक्षिदाह)',
    'akshistravatyupadeha (अक्षिस्त्रावात्युपदेह)',
    'akshishotha (अक्षिशोथ)',
    'redness of eyes (akshiragashrcha, अक्षिरागाश्र्च)',
    'pain (vedana, वेदना)',
    'pimples (pidaka, पिडका)',
    'romodgama (रोमोद्गम)',
    'chimichimayana (चिमिचिमायन)',
    'shothah (शोथाः)',
    'karacharana daha (करचरण दाह)',
    'toda (तोद)',
    'indigestion (avipaka, अविपाक)',
    'headache (shiroruja, शिरोरुजा)',
    'lomaharshakaram (लोमहर्षकरम्)',
    'नासा (nasa, mukha stambha)',
    'nasamupahanti (नासामुपहन्ति)',
    'darshana vikriti (दर्शन विकृती)',
    'pidakashrcha (पिडकाश्र्च)',
    'death (maranam cha, मरणं च)',
    'sukshma damshtra padoasita: (सूक्ष्म दंष्ट्रा पदोअसित:)',
    'niruddharakta: (निरुद्धरक्त:)',
    'kurmabho (कूर्माभो)',
    'prithvarpitah damsho (पृथ्वर्पितः दंशो)',
    'sashothashrcha damsho (सशोथश्र्च दंशो)',
    'pitabha: (पीताभ:)',
    'pitaraktashrcha (पीतरक्तश्र्च)',
    'damsha:pichchhila: (दंश:पिच्छिल:)',
    'sthirashopha krit (स्थिरशोफ कृत्)',
    'snigdha: (स्निग्ध:)',
    'pamdushrcha (पांडुश्र्च)',
    'samdrasrika (सांद्रासृक)',
    'adhodrishti: (अधोदृष्टी:)',
    'svarahina: (स्वरहीन:)',
    'prakampate (प्रकम्पते)',
    'urdhva drishti (ऊर्ध्व दृष्टी)',
    'khupa aradaoroda karane (खूप आरडाओरोड करणे)',
    'sthira sharira (स्थिर शरीर)',
    'stri va purusha donhi chya damshachi lakshane (स्त्री व पुरुष दोन्ही च्या दंशाची लक्षणे)',
    'pamduvaktrastu (पांडुवक्त्रस्तु)',
    'shunaushtho (शूनौष्ठो)',
    'jrimbha (जृम्भा)',
    'krodha (क्रोध)',
    'raktamutravan (रक्तमूत्रावान्)',
    'raktam pidaka (रक्तं पिडका)',
    'sitam pidaka (सितं पिडका)',
    'shyavam pidaka (श्यावं पिडका)',
    'krishnam pidaka (कृष्णं पिडका)',
    'itching (kandu, कण्डू)',
    'visarpapaki (वीसर्पपाकी)',
    'shotho vardhate (शोथो वर्धते)',
    'sogragandhyasrik (सोग्रगन्ध्यसृक्)',
    'akshi gaurava (अक्षि गौरव)',
    'murchchha (मूर्च्छा)',
    'sa rugarta: (स रुगार्त:)',
    'shvasityapi (श्वसित्यपि)',
    'aruchi (अरुची)',
    'damshasya madhye yatkrishnam (दंशस्य मध्ये यत्कृष्णं)',
    'damshasya madhye yatshyavam (दंशस्य मध्ये यत्श्यावं)',
    'va jalakavrittama (वा जालकावृत्तम)',
    'dagdhakriti (दग्धाकृती)',
    'bhrisham paki (भृशं पाकि)',
    'kleda (क्लेद)',
    'shotha (शोथ)',
    'shopha (शोफ)',
    'shveta pidaka (श्वेत पिडका)',
    'asita pidaka (असिता पिडका)',
    'rakta:pidaka (रक्ता:पिडका)',
    'pita va pidaka (पीता वा पिडका)',
    'pranantiko bhavechchhvaso (प्राणान्तिको भवेच्छ्वासो)',
    'shirograha (शिरोग्रह)',
    'adamshachchhonitam pandu (आदंशाच्छोणितं पाण्डु)',
    'lomaharsha (लोमहर्ष)',
    'daha (दाह)',
    'vaivarnya (वैवर्ण्य)',
    'shabdashruti (शब्दाश्रुति)',
    'fever (jvara:, ज्वरा:)',
    'shirogurutvam (शिरोगुरुत्वं)',
    'lalastrava (लालास्त्राव)',
    'raktastrava (रक्तस्त्राव)',
    'shyavatvamatha (श्यावत्वमथ)',
    'nanavarnatvameva va (नानावर्णत्वमेव वा)',
    'moha: (मोह:)',
    'purishabhedashrcha (पुरीषभेदश्र्च)',
    'dahatyaagnirivadau (दहत्यअग्निरिवादौ)',
    'bhinattivordhvamashu cha (भिनत्तीवोर्ध्वमाशु च)',
    'netra nishkriya (नेत्र निष्क्रिय)',
    'ghrana nishkriya (घ्रान निष्क्रिय)',
    'rasana nishkriya (रसना निष्क्रिय)',
    'mamsai: pata (मांसै: पत)',
    'atyartha vedanarto (अत्यर्थ वेदनार्तो)',
    'jahatyasun (जहत्यसून्)',
    'visarpa (विसर्प)',
    'shulam (शुलं)',
    'jvara (ज्वर)',
    'chhardi (छर्दी)',
    'damshashrchaiva vishiryate (दंशश्र्चैव विशीर्यते)',
    'romamcha (रोमांच)',
    'stabdholingo (स्तब्धोलिङ्गो)',
    'bhrishartiman (भृशार्तिमान्)',
    'shitodakeneva siktanyangani (शीतोदकेनेव सिक्तान्यङ्गानि)',
    'ekadamshtrardita: (एकदंष्ट्रार्दीत:)',
    'saruk (सरुक्)',
    'pitaka: (पीतक:)',
    'trishna (तृष्णा)',
    'nidra (निद्रा)',
    'ruja (रुजा)',
    'kandu (कण्डु)',
    'sveda (स्वेद)',
    'alpa shotha (अल्प शोथ)',
    'mamda vedana (मंद वेदना)',
    'sadya:prastravini shyava pidaka (सद्य:प्रस्त्राविणी श्यावा पीडका)',
    'hritpida (हृत्पीडा)',
    'stambha: (स्तंभ:)',
    'siraayama (सिराआयाम)',
    'asthiparvaruk (अस्थिपर्वरुक्)',
    'gatrashyavata (गात्रश्यावता)',
    'samjnanasha (संज्ञानाश)',
    'ushni:shvasau (उष्नि:श्वासौ)',
    'hriddaha: (हृद्दाह:)',
    'katukasyata (कटुकास्यता)',
    'damshavadaranam (दंशावदरणं)',
    'raktapitta (रक्तपित्त)',
    'vamana (वमन)',
    'arochaka (अरोचक)',
    'hrilhasa (हृल्हास)',
    'praseka (प्रसेक)',
    'gauravai: (गौरवै:)',
    'shaitya (शैत्य)',
    'mukhamadhurya (मुखमाधुर्य)',
    'hiccups (hikka, हिक्का)',
    'shvasa (श्वास)',
    'shira:kampa (शिर:कंप)',
    'pain in lateral aspect of chest (parshvashula, पार्श्वशूल)',
    'insomnia (nidranasha, निद्रानाश)',
    'delirium (bahu pralapa, बहू प्रलाप)',
    'body becomes green (harita varnasya sharira, हरित वर्णस्य शरीर)',
    'thirst (trishna, तृष्णा)',
    'burning (daha, दाह)',
    'fever (jvara, ज्वर)',
    'convulsion (murchchha, मूर्च्छा)',
    'diarrhoea (atisara, अतिसार)',
    'Dizziness (bhrama, भ्रम)',
    'vomiting (chhardi, छर्दी)',
    'anorexia (aruchi, अरुची)',
    'Nausea (hrilhasa, हृल्हास)',
    'lethargy (tamdra, तंद्रा)',
    'staimitya (स्तैमित्य)',
    'heaviness (gaurava, गौरव)',
    'shitatecha trasa (शीततेचा त्रास)',
    'more pain in body (shariradu:kha balavata, शरीरदु:ख बलवत)',
    'being unconscious (sammoha, संमोह)',
    'pain in heart region (hridyavyatha, हृद्यव्यथा)',
    'become very thirsty (pratata trishna, प्रतता तृष्णा)',
    'jvara: shitoshnalakshana (ज्वर: शीतोष्णलक्षण)',
    'shira: vidyutatulya vedana (शिर: विद्युततुल्य वेदना)',
    'parshva vidyutatulya vedana (पार्श्व विद्युततुल्य वेदना)',
    'asthi vidyutatulya vedana (अस्थि विद्युततुल्य वेदना)',
    'samdhi vidyutatulya vedana (संधी विद्युततुल्य वेदना)',
    'constant loud yawing (atibala jrimbha, अतिबला जृम्भा)',
    'sphurana (स्फुरण)',
    'sharira kampa: (शरीर कम्प:)',
    'tired (shrama, श्रम)',
    'urovibamdha (उरोविबंध)',
    'cough (kasa, कास)',
    'asthma (shvasa, श्वास)',
    'prajagara (प्रजागर)',
    'ear disorders (karna roga, कर्ण रोग)',
    'eye disorders (akshi roga, अक्षि रोग)',
    'mouth disorders (mukha roga, मुख रोग)',
    'trikagraha: (त्रिकग्रह:)',
    'nausea (hrilhasa, हृल्हास)'
];
